#!/bin/bash
# Demo script showing the difference between cmdgen and agentic

echo "=== warp-term Tools Demo ==="
echo ""
echo "This repository now includes two complementary AI-powered tools:"
echo ""
echo "1. cmdgen - Single Command Generator"
echo "   Purpose: Generate a single shell command from natural language"
echo "   Example: cmdgen 'find files modified in last 7 days'"
echo "   Output: A single command like: find . -type f -mtime -7"
echo ""
echo "2. agentic - Autonomous Task Executor"
echo "   Purpose: Break down complex tasks into multiple steps and execute them"
echo "   Example: agentic 'find all TODO comments in Python files and save to a report'"
echo "   Process:"
echo "     - Plans the task into steps (e.g., find .py files, grep for TODO, save to file)"
echo "     - Generates a command for each step"
echo "     - Executes sequentially with safety confirmations"
echo "     - Maintains context between steps"
echo ""
echo "Both tools use the same Ollama model (gemma3:latest by default) for consistency."
echo ""
echo "Key Features of agentic:"
echo "  ✓ Multi-step task planning"
echo "  ✓ Sequential execution with context"
echo "  ✓ Safety confirmations (interactive mode)"
echo "  ✓ Auto-execution mode (AGENTIC_INTERACTIVE=false)"
echo "  ✓ Spinner feedback during generation"
echo "  ✓ Output capture and context propagation"
echo ""
echo "Installation:"
echo "  chmod +x cmdgen.sh agentic.sh"
echo "  ln -sf \$(pwd)/cmdgen.sh ~/bin/cmdgen"
echo "  ln -sf \$(pwd)/agentic.sh ~/bin/agentic"
echo ""
echo "Try it:"
echo "  cmdgen 'your simple command request'"
echo "  agentic 'your complex multi-step task'"
echo ""
